from fastapi import APIRouter

from app.api.v1 import (
    adr,
    ai_suggest,
    auth,
    bookmarks,
    bpm,
    bpm_assessments,
    bpm_reports,
    bpm_workflow,
    calculations,
    capability_catalogue,
    cards,
    comments,
    diagram_groups,
    diagrams,
    documents,
    eol,
    events,
    favorites,
    file_attachments,
    metamodel,
    migration,
    mutation_batches,
    notifications,
    ppm,
    ppm_reports,
    principles_catalogue,
    process_catalogue,
    relations,
    reports,
    risk_mitigation_tasks,
    risks,
    roles,
    saved_reports,
    servicenow,
    settings,
    soaw,
    stakeholder_roles,
    stakeholders,
    surveys,
    tags,
    todos,
    turbolens,
    users,
    value_stream_catalogue,
    web_portals,
    workspace,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(metamodel.router)
api_router.include_router(cards.router)
api_router.include_router(relations.router)
api_router.include_router(stakeholders.router)
api_router.include_router(comments.router)
api_router.include_router(todos.router)
api_router.include_router(tags.router)
api_router.include_router(documents.router)
api_router.include_router(bookmarks.router)
api_router.include_router(saved_reports.router)
api_router.include_router(reports.router)
api_router.include_router(diagrams.router)
api_router.include_router(diagram_groups.router)
api_router.include_router(soaw.router)
api_router.include_router(eol.router)
api_router.include_router(events.router)
api_router.include_router(mutation_batches.router)
api_router.include_router(users.router)
api_router.include_router(notifications.router)
api_router.include_router(surveys.router)
api_router.include_router(settings.router)
api_router.include_router(web_portals.router)
api_router.include_router(bpm.router)
api_router.include_router(bpm_assessments.router)
api_router.include_router(bpm_reports.router)
api_router.include_router(bpm_workflow.router)
api_router.include_router(roles.router)
api_router.include_router(stakeholder_roles.router)
api_router.include_router(calculations.router)
api_router.include_router(servicenow.router)
api_router.include_router(migration.router)
api_router.include_router(workspace.router)
api_router.include_router(turbolens.router)
api_router.include_router(turbolens.cards_router)
api_router.include_router(turbolens.compliance_router)
api_router.include_router(ai_suggest.router)
api_router.include_router(ppm.router)
api_router.include_router(ppm_reports.router)
api_router.include_router(adr.router)
api_router.include_router(risks.router)
api_router.include_router(risks.cards_risks_router)
api_router.include_router(risk_mitigation_tasks.risks_router)
api_router.include_router(risk_mitigation_tasks.tasks_router)
api_router.include_router(file_attachments.router)
api_router.include_router(favorites.router)
api_router.include_router(capability_catalogue.router)
api_router.include_router(process_catalogue.router)
api_router.include_router(value_stream_catalogue.router)
api_router.include_router(principles_catalogue.router)
